// <auto-generated />
using System;
using InhumanShopApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InhumanShopApp.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241216155620_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Category Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Category name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Medications"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Food"
                        });
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Chat Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("IsFromUser")
                        .HasColumnType("int");

                    b.Property<string>("MessageContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Total price of order");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Order item identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Product Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int")
                        .HasComment("Product count");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)")
                        .HasComment("Product description");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasComment("Product image url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasComment("Product Name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasComment("Product Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasComment("Product quanity");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SizeId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            Count = 50,
                            Description = "High-quality dog food for adult dogs.",
                            ImageUrl = "images/Products/Premium_Dog_Food.jpg",
                            Name = "Premium Dog Food",
                            Price = 45.99m,
                            Quantity = 1,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Count = 20,
                            Description = "Durable scratching post for cats.",
                            ImageUrl = "images/Products/Cat_Scratching_Post.jpg",
                            Name = "Cat Scratching Post",
                            Price = 29.99m,
                            Quantity = 1,
                            SizeId = 4
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Count = 100,
                            Description = "Rubber chew toy to keep your dog entertained.",
                            ImageUrl = "images/Products/Dog_Chew_Toy.jpg",
                            Name = "Dog Chew Toy",
                            Price = 15.49m,
                            Quantity = 1,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Count = 75,
                            Description = "Adjustable cat collar with a small bell.",
                            ImageUrl = "images/Products/Cat_Collar_with_Bell.jpg",
                            Name = "Cat Collar with Bell",
                            Price = 9.99m,
                            Quantity = 1,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Count = 30,
                            Description = "Comfortable bed for medium-sized dogs.",
                            ImageUrl = "images/Products/Dog_And_Cat_Bed.jpg",
                            Name = "Dog And Cat Bed",
                            Price = 59.99m,
                            Quantity = 1,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            Count = 40,
                            Description = "Cat litter with odor-neutralizing technology.",
                            ImageUrl = "images/Products/Cat_Litter-Odor_Control.jpg",
                            Name = "Cat Litter - Odor Control",
                            Price = 19.99m,
                            Quantity = 1,
                            SizeId = 5
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Count = 60,
                            Description = "Gentle shampoo for dogs with sensitive skin.",
                            ImageUrl = "images/Products/Dog_Shampoo-Sensitive_Skin.jpg",
                            Name = "Dog Shampoo - Sensitive Skin",
                            Price = 12.49m,
                            Quantity = 1,
                            SizeId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 5,
                            Count = 200,
                            Description = "Delicious salmon-flavored treats for cats.",
                            ImageUrl = "images/Products/Cat_Treats-Salmon_Flavor.jpg",
                            Name = "Cat Treats - Salmon Flavor",
                            Price = 5.99m,
                            Quantity = 1,
                            SizeId = 2
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Count = 25,
                            Description = "Adjustable harness for comfortable walks.",
                            ImageUrl = "images/Products/Dog_Harness-Adjustable.jpg",
                            Name = "Dog Harness - Adjustable",
                            Price = 24.99m,
                            Quantity = 1,
                            SizeId = 3
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Count = 15,
                            Description = "Interactive tunnel toy for cats to play and hide.",
                            ImageUrl = "images/Products/Cat_Tunnel.jpg",
                            Name = "Cat Tunnel",
                            Price = 34.99m,
                            Quantity = 1,
                            SizeId = 4
                        });
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Size Identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComment("Category name");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "XS"
                        },
                        new
                        {
                            Id = 2,
                            Name = "S"
                        },
                        new
                        {
                            Id = 3,
                            Name = "M"
                        },
                        new
                        {
                            Id = 4,
                            Name = "L"
                        },
                        new
                        {
                            Id = 5,
                            Name = "XL"
                        });
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Status identifier");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = "7699db7d-964f-4782-8209-d76562e0fece",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c64987f3-7852-45a9-bfbe-ae054b33f164",
                            Email = "admin@zooshop.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Belgin",
                            NormalizedEmail = "ADMIN@ZOOSHOP.COM",
                            NormalizedUserName = "ADMIN@ZOOSHOP.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPSjdE3ESS3Vp5Np7dSalQnAneY7BLoV6XDRw3j3eY/gj58Nxq4GNbTQRK9bOyXElA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "adbc5886-0185-48ff-822c-f7e1809d44c7",
                            TwoFactorEnabled = false,
                            UserName = "admin@zooshop.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            ConcurrencyStamp = "6f11f079-c87c-4a81-8a9f-d1e4736c42f4",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "2",
                            ConcurrencyStamp = "5f6702b6-73df-4c48-825f-f165ed593937",
                            Name = "Veterinarian",
                            NormalizedName = "VETERINARIAN"
                        },
                        new
                        {
                            Id = "3",
                            ConcurrencyStamp = "642a22cd-6342-4887-9f14-23e7839b5c13",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "7699db7d-964f-4782-8209-d76562e0fece",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "a1b2c3d4-1234-5678-9876-abcdefabcdef",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "a1b2c3d4-2345-6789-9876-abcdefabcdef",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "a1b2c3d4-3456-7890-9876-abcdefabcdef",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "a1b2c3d4-4567-8901-9876-abcdefabcdef",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "a1b2c3d4-5678-9012-9876-abcdefabcdef",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "a1b2c3d4-6789-0123-9876-abcdefabcdef",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "a1b2c3d4-7890-1234-9876-abcdefabcdef",
                            RoleId = "2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.Veterinarian", b =>
                {
                    b.HasBaseType("InhumanShopApp.Infrastructure.Data.Models.User");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Veterinarian");

                    b.HasData(
                        new
                        {
                            Id = "a1b2c3d4-1234-5678-9876-abcdefabcdef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cfd07ba8-7982-45d8-b919-ad4b4c373b44",
                            Email = "sarah@zooshop.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Sarah Johnson",
                            PasswordHash = "AQAAAAEAACcQAAAAEFBu1r5ttUMJCW3x2IsT9fXUEDhiRivEZj1Wg7G1HcLb6CxcsYHGdOr0jt56WPUVwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f4c054e3-c2bf-45a0-8ebc-0507ad76d549",
                            TwoFactorEnabled = false,
                            Specialization = "Small Animals",
                            TelNumber = "+359888123456",
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = "a1b2c3d4-2345-6789-9876-abcdefabcdef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7c061e07-e54f-4a67-aeef-3464969f5edc",
                            Email = "michael@zooshop.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Michael Brown",
                            PasswordHash = "AQAAAAEAACcQAAAAELE1ZPNmBqFE7nzZWxgiEmewbhTqrdc2Bx9DiEYTAlrWkSeRHQAEiIBevpGNC7tFAg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "705b0bf9-051c-43c3-88cc-a878b3b7c6f0",
                            TwoFactorEnabled = false,
                            Specialization = "Exotic Animals",
                            TelNumber = "+359888654321",
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = "a1b2c3d4-3456-7890-9876-abcdefabcdef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "166d39c3-82ba-4057-a353-d933138706e0",
                            Email = "emma@zooshop.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Emma Davis",
                            PasswordHash = "AQAAAAEAACcQAAAAEBOs/tmSxn+y8IloY/y1dq3Az5kNYKIzVAqTVHaXtNgOW7lvCQjlufExSqxoTvNUdQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "27cbb609-2de0-4405-8f6f-fa374b5cf1c7",
                            TwoFactorEnabled = false,
                            Specialization = "Large Animals",
                            TelNumber = "+359888987654",
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = "a1b2c3d4-4567-8901-9876-abcdefabcdef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b0dd164a-ff40-417a-b967-60db64c695bb",
                            Email = "john@zooshop.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. John Smith",
                            PasswordHash = "AQAAAAEAACcQAAAAENy32nghSsFmPMZWowIzxGnvRRohUdOAw86S+e2RrigKUoCbsDHknGbb+FxSIeV4kA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "10d1db54-5d4e-48c3-b7d0-a92b7d771551",
                            TwoFactorEnabled = false,
                            Specialization = "Birds",
                            TelNumber = "+359888456789",
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = "a1b2c3d4-5678-9012-9876-abcdefabcdef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "adc4fad7-dd4a-4872-952a-864e1d5e9299",
                            Email = "olivia@zooshop.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Olivia Wilson",
                            PasswordHash = "AQAAAAEAACcQAAAAENy2+4LbSpespP5oH6gdI1unuCRdCmYXIfyPpgeSONmkPtrpJEjgQlLHu/87vd7mkg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "02696368-0f23-4c26-971b-96d006166e62",
                            TwoFactorEnabled = false,
                            Specialization = "Reptiles",
                            TelNumber = "+359888123789",
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = "a1b2c3d4-6789-0123-9876-abcdefabcdef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "33ef44dc-65ae-4c37-8e8c-61876fe6b6d5",
                            Email = "william@zooshop.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. William Garcia",
                            PasswordHash = "AQAAAAEAACcQAAAAEEDexIyPn7WgQCE8qUi+vCBBex3ZrSphMmmOnBF0//VV1tECKAxX5xdPUJ5PIs5/Tw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9ed6d645-b679-466e-a06f-81a1edd81271",
                            TwoFactorEnabled = false,
                            Specialization = "Fish",
                            TelNumber = "+359888654987",
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = "a1b2c3d4-7890-1234-9876-abcdefabcdef",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "569dc501-b972-4910-907f-c9d2a3bf0047",
                            Email = "sophia@zooshop.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            Name = "Dr. Sophia Martinez",
                            PasswordHash = "AQAAAAEAACcQAAAAEM+Uw3GUq2qAXvM90r0bljUyu87u5LNEVmaIxZOCNL3udTO/vfd4mQWnis+ACX74dg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "054e614e-36a9-4f21-b033-ea5cf1156079",
                            TwoFactorEnabled = false,
                            Specialization = "Wildlife",
                            TelNumber = "+359888987123",
                            YearsOfExperience = 15
                        });
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.Chat", b =>
                {
                    b.HasOne("InhumanShopApp.Infrastructure.Data.Models.User", "User")
                        .WithMany("Chats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.Order", b =>
                {
                    b.HasOne("InhumanShopApp.Infrastructure.Data.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InhumanShopApp.Infrastructure.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.OrderItem", b =>
                {
                    b.HasOne("InhumanShopApp.Infrastructure.Data.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InhumanShopApp.Infrastructure.Data.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.Product", b =>
                {
                    b.HasOne("InhumanShopApp.Infrastructure.Data.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InhumanShopApp.Infrastructure.Data.Models.Size", "Size")
                        .WithMany("Products")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("InhumanShopApp.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("InhumanShopApp.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InhumanShopApp.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("InhumanShopApp.Infrastructure.Data.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.Size", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("InhumanShopApp.Infrastructure.Data.Models.User", b =>
                {
                    b.Navigation("Chats");
                });
#pragma warning restore 612, 618
        }
    }
}
